[tool.pytest.ini_options]
addopts = "-q --cov=app --cov-report=term-missing --cov-fail-under=85"

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
pretty = true

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
